# Generated by Django 3.0.5 on 2022-10-21 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_quetion1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quetion1',
            new_name='Question1',
        ),
    ]
