# Generated by Django 3.0.5 on 2022-10-21 22:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_question2'),
    ]

    operations = [
        migrations.AddField(
            model_name='question1',
            name='resp',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
