# Generated by Django 3.0.5 on 2022-10-21 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_question1_resp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question1',
            name='resp',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
