from django.test import TestCase

from student.models import Ability


class TestAddAbilities(TestCase):
    @classmethod
    def test_set_abilities(cls):
        abilities = [];
        #   Gestión de BD:
        abilities.append('diseño')
        abilities.append('SQL')
        abilities.append('Oracle')
        abilities.append('MySql')
        abilities.append('Microsoft SQL Server')
        abilities.append('PostgreSQL')
        abilities.append('SQLite')
        abilities.append('Redis')
        abilities.append('MongoDB')
        abilities.append('Oracle')
        abilities.append('AWS RDS')
        #     Programación:
        abilities.append('Python')
        abilities.append('c')
        abilities.append('c++')
        abilities.append('java')
        abilities.append('C#')
        abilities.append('HTML')
        abilities.append('CSS')
        abilities.append('JavaScript')
        abilities.append('Ruby')
        abilities.append('PHP')
        abilities.append('Swift')
        abilities.append('Go')
        abilities.append('Kotlin')
        abilities.append('R')
        abilities.append('Rust')
        abilities.append('Perl')
        abilities.append('Matlab')
        # Web Development Frameworks:
        abilities.append('React')
        abilities.append('Angular')
        abilities.append('Vue.js')
        abilities.append('Django')
        abilities.append('Node.js')
        abilities.append('Flask')
        abilities.append('ASP.NET Core')
        abilities.append('Spring Boot')
        abilities.append('ASP.NET')
        abilities.append('Laravel')
        abilities.append('Symfony')
        abilities.append('Express')
        #   Mobile Framework
        abilities.append('React Native')
        abilities.append('Flutter')
        abilities.append('Xamarin')
        abilities.append('Ionic')
        abilities.append('NativeScript')
        abilities.append('Flutter')
        # Desktop Development Frameworks:
        abilities.append('Electron')
        #   Cloud Platforms and Services:
        abilities.append('Amazon Web Services (AWS)')
        abilities.append('Microsoft Azure')
        abilities.append('Google Cloud Platform (GCP)')
        abilities.append('Heroku')
        abilities.append('IBM Cloud')
        abilities.append('Firebase')
        #   DevOps Tools:
        abilities.append('Docker')
        abilities.append('Kubernetes')
        abilities.append('GitLab CI/CD')
        abilities.append('Travis CI')
        abilities.append('Ansible')
        abilities.append('Puppet')
        abilities.append('Chef')
        #   Testing Frameworks:
        abilities.append('JUnit')
        abilities.append('Selenium')
        abilities.append('Cypress')
        abilities.append('pytest')
        abilities.append('Jest')
        abilities.append('Mockito')
        #   Frontend Development Tools:
        abilities.append('Sass')
        abilities.append('Less')
        abilities.append('Bootstrap')
        abilities.append('Tailwind CSS')
        abilities.append('Webpack')
        #   Version Control Systems:
        abilities.append('Git')
        abilities.append('Subversion (SVN)')
        abilities.append('Mercurial')
        #   Integrated Development Environments (IDEs):
        abilities.append('Visual Studio')
        abilities.append('Eclipse')
        abilities.append('IntelliJ IDEA')
        abilities.append('NetBeans')
        abilities.append('Android Studio')
        abilities.append('PyCharm')
        abilities.append('PHPStorm')
        abilities.append('Xcode')
        #   Code Editors:
        abilities.append('Visual Studio Code')
        abilities.append('Sublime Text')
        abilities.append('Notepad++')
        abilities.append('Vim')
        abilities.append('Emacs')
        #   APIS
        abilities.append('Postman')
        # Redes
        abilities.append('Http')
        abilities.append('Https')
        abilities.append('DNS')
        abilities.append('DHCP')
        abilities.append('Socket')
        abilities.append('Direccionamiento IP')
        abilities.append('Firewall')
        abilities.append('VPN')
        abilities.append('Antivirus')
        abilities.append('IDS')
        abilities.append('IPS')
        #   tools
        abilities.append('Wireshark')
        abilities.append('Nmap')
        abilities.append('Metasploit Framework')
        abilities.append('Nessus')
        abilities.append('Snort')
        abilities.append('Burp Suite')
        abilities.append('OpenVAS')
        abilities.append('Tcpdump')
        abilities.append('Aircrack-ng')
        abilities.append('Splunk')
        abilities.append('ArcSight')
        abilities.append('LogRhythm')
        #   servers
        abilities.append('Apache')
        abilities.append('Nginx')
        abilities.append('Active Directory')
        #   Operative Systems
        abilities.append('Windows Server')
        abilities.append('Linux')
        abilities.append('CenTos')
        abilities.append('CaliLinux')
        abilities.append('Debian')
        abilities.append('Nova')
        abilities.append('Unix')
        abilities.append('FreeBSD')
        abilities.append('VMware ESXi')
        abilities.append('Citrix XenServer')
        abilities.append('IBM z/OS')
        #   Methodologies
        abilities.append('Scrum')
        abilities.append('XP (Programación Extrema)')
        abilities.append('Kanban')
        abilities.append('Lean')
        abilities.append('Crystal')
        abilities.append('Dynamic Systems Development Method (DSDM)')
        abilities.append('Feature Driven Development (FDD)')
        abilities.append('Adaptive Software Development (ASD)')
        abilities.append('Agile Unified Process (AUP)')
        abilities.append('Agile Modeling (AM)')
        abilities.append('Agile Data Method (ADM)')
        abilities.append('Agile Project Management (APM)')
        abilities.append('Lean Software Development (LSD)')
        abilities.append('Scaled Agile Framework (SAFe)')
        abilities.append('Disciplined Agile Delivery (DAD)')
        abilities.append('Nexus')
        abilities.append('RUP')
        abilities.append('AUP UCI')
        for h in abilities:
            print(h)
            a = Ability(ability=h)
            a.save()
